from vpython import vector, color

NUM_CYLINDERS = 4
CYLINDER_SPACING = 3.5

CYLINDER_RADIUS = 1.2
CYLINDER_HEIGHT = 4.0
CYLINDER_WALL_THICKNESS = 0.15

PISTON_RADIUS = 1.05
PISTON_HEIGHT = 1.2

STROKE_LENGTH = 2.0
CONNECTING_ROD_LENGTH = 3.5

CRANKSHAFT_RADIUS = 0.6
CRANKSHAFT_LENGTH = (NUM_CYLINDERS - 1) * CYLINDER_SPACING + 4
CRANK_PIN_RADIUS = 0.35
CRANK_THROW = STROKE_LENGTH / 2

CAMSHAFT_RADIUS = 0.25
CAMSHAFT_LENGTH = CRANKSHAFT_LENGTH
CAM_HEIGHT = 0.5
CAM_RADIUS = 0.4

VALVE_RADIUS = 0.2
VALVE_STEM_LENGTH = 1.5
VALVE_HEAD_RADIUS = 0.45
VALVE_LIFT = 0.3

CYLINDER_HEAD_HEIGHT = 1.5

SPARK_PLUG_LENGTH = 0.8
SPARK_PLUG_RADIUS = 0.12

ENGINE_BLOCK_HEIGHT = CYLINDER_HEIGHT + CYLINDER_HEAD_HEIGHT + 3.0
ENGINE_BLOCK_WIDTH = CYLINDER_RADIUS * 2 + 1.5
ENGINE_BLOCK_LENGTH = (NUM_CYLINDERS - 1) * CYLINDER_SPACING + 4

BASE_POSITION = vector(0, 0, 0)

STROKES = [
    {"name": "进气冲程", "name_en": "Intake Stroke", "color": color.blue},
    {"name": "压缩冲程", "name_en": "Compression Stroke", "color": color.orange},
    {"name": "做功冲程", "name_en": "Power Stroke", "color": color.red},
    {"name": "排气冲程", "name_en": "Exhaust Stroke", "color": color.green},
]

FIRING_ORDER = [0, 2, 3, 1]

STROKE_DURATION = 720 / 4

RPM = 600
DEGREES_PER_FRAME = (RPM / 60) * 360 / 60
